{{- if and .Values.defaultBackend.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "n42-gateway.labels" . | nindent 4 }}
  name: {{ include "n42-gateway.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
